### ISSUE TITLE
does program have a license?

### ISSUE THREAD

**Issue by LordCommanderMay** [TomSchimansky/GuitarTuner#1]
hello, I would like to use some your code for my project but I can not do that if this code does not have a license.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by TomSchimansky** [comment]
Of course you can use the code, I added a GNU General Public License. If you use my code a lot, it would be nice if you could link this project somehow if you publish yours as well.

**Comment by LordCommanderMay** [comment]
of course Thank you!
